/**
 * Fetches the baked registry JSON over HTTP. A short module-level
 * memoization avoids hammering the registry CDN when the host AI
 * fires several tool calls in quick succession (e.g. a `search`
 * followed by a `get`). The TTL is intentionally short — 30 seconds
 * — so newly published artifacts show up within a window the user
 * won't perceive as stale.
 *
 * Failure modes are wrapped with domain-specific context so callers
 * (the tool handlers) can surface readable errors rather than raw
 * `TypeError: fetch failed` or `SyntaxError: Unexpected token <`.
 */
import { registryUrl } from "./env.js";
import type { Registry } from "./types.js";

export interface FetchOptions {
  /** Override the URL — handy for tests. Defaults to {@link registryUrl}. */
  url?: string;
  /** Custom fetcher — defaults to global `fetch`. Tests inject mocks. */
  fetcher?: typeof fetch;
}

const FETCH_TIMEOUT_MS = 5000;

/** In-memory TTL for the catalog. Short enough that publishers see new
 *  artifacts within a perceptible window after `mh publish`. */
export const REGISTRY_CACHE_TTL_MS = 30_000;

let cached: { value: Registry; fetchedAt: number } | null = null;

export async function fetchRegistry(opts: FetchOptions = {}): Promise<Registry> {
  const now = Date.now();
  if (cached && now - cached.fetchedAt < REGISTRY_CACHE_TTL_MS) {
    return cached.value;
  }
  const url = opts.url ?? registryUrl();
  const fetcher = opts.fetcher ?? fetch;
  let res: Response;
  try {
    res = await fetcher(url, {
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
  } catch (err) {
    throw new Error(`Could not reach MetaHub registry at ${url}: ${(err as Error).message}`, {
      cause: err,
    });
  }
  if (!res.ok) {
    throw new Error(`MetaHub registry at ${url} returned HTTP ${res.status}`);
  }
  let payload: unknown;
  try {
    payload = await res.json();
  } catch (err) {
    throw new Error(
      `MetaHub registry payload at ${url} is not valid JSON: ${(err as Error).message}`,
      { cause: err },
    );
  }
  const value = normalise(payload);
  cached = { value, fetchedAt: now };
  return value;
}

/**
 * Clears the in-memory catalog cache. Exposed for tests that inject
 * fresh fetchers — without this, the second test in a file would see
 * the first test's cached payload and never call the new mock.
 */
export function clearRegistryCache(): void {
  cached = null;
}

/**
 * Normalise the JSON payload into a {@link Registry}. The registry
 * file is generated by `apps/registry/src/lib/registry/build.ts`, so
 * we only do shallow shape-checking here — anything bad is a build
 * regression upstream, not something the MCP server should silently
 * paper over.
 */
function normalise(raw: unknown): Registry {
  if (!raw || typeof raw !== "object") {
    throw new Error("Registry payload is not an object");
  }
  const obj = raw as Partial<Registry>;
  if (!Array.isArray(obj.items)) {
    throw new Error("Registry payload missing `items` array");
  }
  return {
    items: obj.items,
    generatedAt: obj.generatedAt ?? new Date(0).toISOString(),
    counts: obj.counts ?? { skill: 0, mcp: 0, agent: 0, plugin: 0 },
  };
}
